### ISSUE TITLE
why is locations required if we acknowledge cases where they may not be available?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#75] opened 2015-12-19 16:22 UTC
As noted in the spec, an analysis might fire results noting that certain things could not be observed across an analysis target. This issue also touches on the problem of general logging. If a SARIF producer wants to emit some general output, they must currently provide a rule id and location for each logging message. I suggest we drop the requirement to express locations, noting the unusual circumstances under which they aren't produced (general logging, analysis noting the absence of desired conditions).

6.9.6. locations property

A result object shall contain a property named locations whose value is an array, each of whose elements is a location object (§6.10) which specifies a location where the result occurred. The locations array shall contain at least one element if the result can be associated with a location. In rare circumstances, it might not be possible to specify a location for a result.

**Comment by ghost** [comment] 2016-02-27 19:23
Duplicate of #118 (which is now fixed).

**Closed as completed by ghost** 2016-02-27 19:23 UTC
Labels: resolved-duplicate
