### ISSUE TITLE
Make ruleId optional for notes?

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#76] opened 2015-12-19 16:24 UTC
We should consider making ruleId optional for notes. We could also consider making ruleId optional for everything except error and warning. I'd be happy simply to make it optional for notes at this point.

**Comment by michaelcfanning** [comment] 2016-01-14 17:32
@lgolding @vscottlouvau

bumping this issue. when using SARIF to hold search/grep results, there's no real need for a rule id. in this scenario, SARIF is just a useful code annotation mechanism.

**Comment by ghost** [comment] 2016-02-27 19:21
Duplicate of #96 (which is now fixed).

**Closed as completed by ghost** 2016-02-27 19:21 UTC
Labels: resolved-duplicate
