### ISSUE TITLE
Add snippet member to annotatedCodeLocation

### ISSUE THREAD

**Issue by michaelcfanning** [sarif-standard/sarif-spec#235] opened 2016-06-29 17:19 UTC
Should we add a 'snippet' member to annotatedCodeLocation? static driver verifier uses a snippet in order to construct its trace tree. This suggestion makes most sense if something useful can be done with this data when source is otherwise note available (or if the snippet associated with an ACL is different from the source code associated with the ALC region). If the result can only actually be understood/navigated when source is available, then we could require viewers to generate snippet-driven views by extracting them from the source code (using the region data).

**Comment by ghost** [comment] 2016-07-11 21:38
We both adding this issue on the same day. Closed duplicate of #237, which is fixed.

**Closed as completed by ghost** 2016-07-11 21:38 UTC
Labels: enhancement, resolved-fixed, impact-non-breaking-change
